# Testing that an invalid write is not carried into the next write, after a file is closed.

if "testfile.txt.a" in listfiles():
  removefile("testfile.txt.a")
if "testfile.txt.b" in listfiles():
  removefile("testfile.txt.b")

# Create a new file
try:
  myfile=ABopenfile("testfile.txt",True)  #Create an AB file
except:
  log("can't open a new file\n")
  exitall()

# I should get 'SE' when reading an empty file...
try: 
  assert('SE' == myfile.readat(None,0))
except:
  log("afile is not valid-at-birth\n")
  exitall()

# put some invalid data in the file.
try:
  myfile.writeat("sinvalidE",0)
except:
  log("writing to the file fails\n")
  exitall()

# I should still get 'SE' because the file wasn't closed.
try: 
  assert('SE' == myfile.readat(None,0))
except:
  log("afile was changed by a bfile write\n")
  exitall()

# Close the file
try:
  myfile.close()
except:
  log("Can't close my file")
  exitall()

# Open the file up again, create is false.
try: 
  myfile = ABopenfile("testfile.txt", False)
except:
  log("Can't open the file I just made\n")
  exitall()

# A read should return SE.
try:
  assert('SE' == myfile.readat(None,0))
except:
  log("File has the wrong contents\n")  
  exitall()

# put some valid data in the file.
try:
  myfile.writeat("SvalidE",0)
except:
  log("Writing to the file fails\n")
  exitall()

# Close the file
try:
  myfile.close()
except:
  log("Can't close my file")
  exitall()

# Open the file again
try: 
  myfile = ABopenfile("testfile.txt", False)
except:
  log("Can't open the file I just made\n")
  exitall()

# A read should return valid write, and nothing else.
try:
  assert('SvalidE' == myfile.readat(None,0))
except:
  log("The file doesn't have the right contents\n")  
  exitall()